"""add org team enrollment

Revision ID: 4a5ff97758ce
Revises: 01b4a85743a7
Create Date: 2026-07-06 18:55:00.939688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5ff97758ce'
down_revision: Union[str, None] = '01b4a85743a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Enum('headquarters', 'branch', name='org_level', native_enum=False, length=16), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('registration_no', sa.String(length=64), nullable=True),
    sa.Column('charter_file', sa.String(length=512), nullable=True),
    sa.Column('contact_name', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organizations_level'), 'organizations', ['level'], unique=False)
    op.create_index(op.f('ix_organizations_parent_id'), 'organizations', ['parent_id'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('home_course', sa.String(length=128), nullable=True),
    sa.Column('logo', sa.String(length=512), nullable=True),
    sa.Column('charter', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['captain_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_branch_id'), 'teams', ['branch_id'], unique=False)
    op.create_index(op.f('ix_teams_captain_id'), 'teams', ['captain_id'], unique=False)
    op.create_index(op.f('ix_teams_is_deleted'), 'teams', ['is_deleted'], unique=False)
    op.create_table('team_enrollments',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending_captain', 'pending_branch', 'approved', 'rejected', name='enrollment_status', native_enum=False, length=24), nullable=False),
    sa.Column('captain_reviewed_by', sa.Integer(), nullable=True),
    sa.Column('captain_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch_reviewed_by', sa.Integer(), nullable=True),
    sa.Column('branch_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_enrollments_is_deleted'), 'team_enrollments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_team_enrollments_status'), 'team_enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_team_enrollments_team_id'), 'team_enrollments', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_enrollments_user_id'), 'team_enrollments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_enrollments_user_id'), table_name='team_enrollments')
    op.drop_index(op.f('ix_team_enrollments_team_id'), table_name='team_enrollments')
    op.drop_index(op.f('ix_team_enrollments_status'), table_name='team_enrollments')
    op.drop_index(op.f('ix_team_enrollments_is_deleted'), table_name='team_enrollments')
    op.drop_table('team_enrollments')
    op.drop_index(op.f('ix_teams_is_deleted'), table_name='teams')
    op.drop_index(op.f('ix_teams_captain_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_branch_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_organizations_parent_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_level'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
