"""extend course fields

Revision ID: a6b7c8d9e0f1
Revises: f5a6b7c8d9e0
Create Date: 2026-07-27 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b7c8d9e0f1'
down_revision: Union[str, None] = 'f5a6b7c8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('courses', sa.Column('holes', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('par', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('rating', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('courses', sa.Column('slope', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'slope')
    op.drop_column('courses', 'rating')
    op.drop_column('courses', 'par')
    op.drop_column('courses', 'holes')
    op.drop_column('courses', 'city')
    # ### end Alembic commands ###
