"""add courses and competitions

Revision ID: b1c2d3e4f5a6
Revises: a9b3c2d1e4f5
Create Date: 2026-07-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5a6'
down_revision: Union[str, None] = 'a9b3c2d1e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('name_zh', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('contact_name', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_is_active'), 'courses', ['is_active'], unique=False)
    op.create_index(op.f('ix_courses_is_deleted'), 'courses', ['is_deleted'], unique=False)

    op.create_table('competitions',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('competition_type', sa.Enum('official', 'team', 'invitation', 'social', 'training', name='competition_type', native_enum=False, length=16), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('max_handicap', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', 'playing', 'review', 'completed', 'cancelled', name='competition_status', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_competition_type'), 'competitions', ['competition_type'], unique=False)
    op.create_index(op.f('ix_competitions_course_id'), 'competitions', ['course_id'], unique=False)
    op.create_index(op.f('ix_competitions_branch_id'), 'competitions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_competitions_status'), 'competitions', ['status'], unique=False)
    op.create_index(op.f('ix_competitions_is_deleted'), 'competitions', ['is_deleted'], unique=False)

    op.create_table('competition_registrations',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('registration_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'paid', 'waived', name='competition_reg_payment_status', native_enum=False, length=16), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='competition_reg_approval_status', native_enum=False, length=16), nullable=False),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_registrations_competition_id'), 'competition_registrations', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_registrations_member_id'), 'competition_registrations', ['member_id'], unique=False)
    op.create_index(op.f('ix_competition_registrations_user_id'), 'competition_registrations', ['user_id'], unique=False)
    op.create_index(op.f('ix_competition_registrations_team_id'), 'competition_registrations', ['team_id'], unique=False)
    op.create_index(op.f('ix_competition_registrations_payment_status'), 'competition_registrations', ['payment_status'], unique=False)
    op.create_index(op.f('ix_competition_registrations_approval_status'), 'competition_registrations', ['approval_status'], unique=False)
    op.create_index(op.f('ix_competition_registrations_is_deleted'), 'competition_registrations', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competition_registrations_is_deleted'), table_name='competition_registrations')
    op.drop_index(op.f('ix_competition_registrations_approval_status'), table_name='competition_registrations')
    op.drop_index(op.f('ix_competition_registrations_payment_status'), table_name='competition_registrations')
    op.drop_index(op.f('ix_competition_registrations_team_id'), table_name='competition_registrations')
    op.drop_index(op.f('ix_competition_registrations_user_id'), table_name='competition_registrations')
    op.drop_index(op.f('ix_competition_registrations_member_id'), table_name='competition_registrations')
    op.drop_index(op.f('ix_competition_registrations_competition_id'), table_name='competition_registrations')
    op.drop_table('competition_registrations')

    op.drop_index(op.f('ix_competitions_is_deleted'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_status'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_branch_id'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_course_id'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_competition_type'), table_name='competitions')
    op.drop_table('competitions')

    op.drop_index(op.f('ix_courses_is_deleted'), table_name='courses')
    op.drop_index(op.f('ix_courses_is_active'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
