"""add grouping

Revision ID: c2d3e4f5a6b7
Revises: b1c2d3e4f5a6
Create Date: 2026-07-27 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d3e4f5a6b7'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_groups',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('tee_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starting_hole', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'playing', 'completed', name='group_status', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_groups_competition_id'), 'competition_groups', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_groups_status'), 'competition_groups', ['status'], unique=False)
    op.create_index(op.f('ix_competition_groups_is_deleted'), 'competition_groups', ['is_deleted'], unique=False)

    op.create_table('competition_group_players',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('handicap', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['competition_groups.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['competition_registrations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_group_players_competition_id'), 'competition_group_players', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_group_players_group_id'), 'competition_group_players', ['group_id'], unique=False)
    op.create_index(op.f('ix_competition_group_players_member_id'), 'competition_group_players', ['member_id'], unique=False)
    op.create_index(op.f('ix_competition_group_players_registration_id'), 'competition_group_players', ['registration_id'], unique=False)
    op.create_index(op.f('ix_competition_group_players_team_id'), 'competition_group_players', ['team_id'], unique=False)
    op.create_index(op.f('ix_competition_group_players_is_deleted'), 'competition_group_players', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competition_group_players_is_deleted'), table_name='competition_group_players')
    op.drop_index(op.f('ix_competition_group_players_team_id'), table_name='competition_group_players')
    op.drop_index(op.f('ix_competition_group_players_registration_id'), table_name='competition_group_players')
    op.drop_index(op.f('ix_competition_group_players_member_id'), table_name='competition_group_players')
    op.drop_index(op.f('ix_competition_group_players_group_id'), table_name='competition_group_players')
    op.drop_index(op.f('ix_competition_group_players_competition_id'), table_name='competition_group_players')
    op.drop_table('competition_group_players')

    op.drop_index(op.f('ix_competition_groups_is_deleted'), table_name='competition_groups')
    op.drop_index(op.f('ix_competition_groups_status'), table_name='competition_groups')
    op.drop_index(op.f('ix_competition_groups_competition_id'), table_name='competition_groups')
    op.drop_table('competition_groups')
    # ### end Alembic commands ###
