"""add members table

Revision ID: cc8bffcbca1e
Revises: 4a5ff97758ce
Create Date: 2026-07-06 19:28:52.037853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8bffcbca1e'
down_revision: Union[str, None] = '4a5ff97758ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chinese_name', sa.String(length=64), nullable=False),
    sa.Column('english_name', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('golf_age', sa.Integer(), nullable=True),
    sa.Column('club_number', sa.String(length=32), nullable=True),
    sa.Column('handicap', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('nz_address', sa.String(length=256), nullable=True),
    sa.Column('local_phone', sa.String(length=32), nullable=True),
    sa.Column('passport_no', sa.String(length=64), nullable=True),
    sa.Column('visa_type', sa.String(length=64), nullable=True),
    sa.Column('payment_account', sa.String(length=128), nullable=True),
    sa.Column('emergency_contact', sa.String(length=128), nullable=True),
    sa.Column('level', sa.Enum('honorary', 'formal', 'probationary', 'blacklist', name='member_level', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('active', 'sleeping', 'cancelled', name='member_status', native_enum=False, length=16), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_branch_id'), 'members', ['branch_id'], unique=False)
    op.create_index(op.f('ix_members_is_deleted'), 'members', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_members_level'), 'members', ['level'], unique=False)
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    op.create_index(op.f('ix_members_team_id'), 'members', ['team_id'], unique=False)
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_index(op.f('ix_members_team_id'), table_name='members')
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_index(op.f('ix_members_level'), table_name='members')
    op.drop_index(op.f('ix_members_is_deleted'), table_name='members')
    op.drop_index(op.f('ix_members_branch_id'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
