"""add scoring

Revision ID: d3e4f5a6b7c8
Revises: c2d3e4f5a6b7
Create Date: 2026-07-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e4f5a6b7c8'
down_revision: Union[str, None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hole_columns = [sa.Column(f'hole{i}', sa.Integer(), nullable=True) for i in range(1, 19)]

    op.create_table('score_cards',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    *hole_columns,
    sa.Column('out_score', sa.Integer(), nullable=True),
    sa.Column('in_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('handicap_snapshot', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('net_score', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'checking', 'approved', 'rejected', name='score_card_status', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['competition_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_cards_competition_id'), 'score_cards', ['competition_id'], unique=False)
    op.create_index(op.f('ix_score_cards_member_id'), 'score_cards', ['member_id'], unique=False)
    op.create_index(op.f('ix_score_cards_group_id'), 'score_cards', ['group_id'], unique=False)
    op.create_index(op.f('ix_score_cards_status'), 'score_cards', ['status'], unique=False)
    op.create_index(op.f('ix_score_cards_is_deleted'), 'score_cards', ['is_deleted'], unique=False)

    op.create_table('score_reviews',
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'checking', 'approved', 'rejected', name='score_review_status', native_enum=False, length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['score_cards.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_reviews_score_id'), 'score_reviews', ['score_id'], unique=False)
    op.create_index(op.f('ix_score_reviews_reviewer_id'), 'score_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_score_reviews_status'), 'score_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_score_reviews_is_deleted'), 'score_reviews', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_reviews_is_deleted'), table_name='score_reviews')
    op.drop_index(op.f('ix_score_reviews_status'), table_name='score_reviews')
    op.drop_index(op.f('ix_score_reviews_reviewer_id'), table_name='score_reviews')
    op.drop_index(op.f('ix_score_reviews_score_id'), table_name='score_reviews')
    op.drop_table('score_reviews')

    op.drop_index(op.f('ix_score_cards_is_deleted'), table_name='score_cards')
    op.drop_index(op.f('ix_score_cards_status'), table_name='score_cards')
    op.drop_index(op.f('ix_score_cards_group_id'), table_name='score_cards')
    op.drop_index(op.f('ix_score_cards_member_id'), table_name='score_cards')
    op.drop_index(op.f('ix_score_cards_competition_id'), table_name='score_cards')
    op.drop_table('score_cards')
    # ### end Alembic commands ###
