"""add activities

Revision ID: e42909fa4cfc
Revises: cc8bffcbca1e
Create Date: 2026-07-06 20:52:05.433695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42909fa4cfc'
down_revision: Union[str, None] = 'cc8bffcbca1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.Enum('weekly_round', 'team_building', 'course_visit', 'networking', 'newbie_salon', name='activity_type', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'closed', 'cancelled', name='activity_status', native_enum=False, length=16), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('course_name', sa.String(length=128), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('max_family_slots', sa.Integer(), nullable=False),
    sa.Column('family_allowed', sa.Boolean(), nullable=False),
    sa.Column('course_slots_locked', sa.Boolean(), nullable=False),
    sa.Column('checkin_token', sa.String(length=32), nullable=False),
    sa.Column('simple_scoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_branch_id'), 'activities', ['branch_id'], unique=False)
    op.create_index(op.f('ix_activities_checkin_token'), 'activities', ['checkin_token'], unique=False)
    op.create_index(op.f('ix_activities_is_deleted'), 'activities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_activities_status'), 'activities', ['status'], unique=False)
    op.create_index(op.f('ix_activities_team_id'), 'activities', ['team_id'], unique=False)
    op.create_table('activity_registrations',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registrant_type', sa.Enum('member', 'family', name='registrant_type', native_enum=False, length=16), nullable=False),
    sa.Column('family_name', sa.String(length=64), nullable=True),
    sa.Column('family_relation', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('registered', 'checked_in', 'absent', 'cancelled', name='registration_status', native_enum=False, length=16), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_strokes', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_registrations_activity_id'), 'activity_registrations', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_registrations_is_deleted'), 'activity_registrations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_activity_registrations_member_id'), 'activity_registrations', ['member_id'], unique=False)
    op.create_index(op.f('ix_activity_registrations_registrant_type'), 'activity_registrations', ['registrant_type'], unique=False)
    op.create_index(op.f('ix_activity_registrations_status'), 'activity_registrations', ['status'], unique=False)
    op.create_index(op.f('ix_activity_registrations_user_id'), 'activity_registrations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_registrations_user_id'), table_name='activity_registrations')
    op.drop_index(op.f('ix_activity_registrations_status'), table_name='activity_registrations')
    op.drop_index(op.f('ix_activity_registrations_registrant_type'), table_name='activity_registrations')
    op.drop_index(op.f('ix_activity_registrations_member_id'), table_name='activity_registrations')
    op.drop_index(op.f('ix_activity_registrations_is_deleted'), table_name='activity_registrations')
    op.drop_index(op.f('ix_activity_registrations_activity_id'), table_name='activity_registrations')
    op.drop_table('activity_registrations')
    op.drop_index(op.f('ix_activities_team_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_status'), table_name='activities')
    op.drop_index(op.f('ix_activities_is_deleted'), table_name='activities')
    op.drop_index(op.f('ix_activities_checkin_token'), table_name='activities')
    op.drop_index(op.f('ix_activities_branch_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
