"""add ranking

Revision ID: e4f5a6b7c8d9
Revises: d3e4f5a6b7c8
Create Date: 2026-07-27 13:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f5a6b7c8d9'
down_revision: Union[str, None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rankings',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('individual', 'team', name='ranking_scope', native_enum=False, length=16), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('award', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rankings_competition_id'), 'rankings', ['competition_id'], unique=False)
    op.create_index(op.f('ix_rankings_scope'), 'rankings', ['scope'], unique=False)
    op.create_index(op.f('ix_rankings_member_id'), 'rankings', ['member_id'], unique=False)
    op.create_index(op.f('ix_rankings_team_id'), 'rankings', ['team_id'], unique=False)
    op.create_index(op.f('ix_rankings_is_deleted'), 'rankings', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rankings_is_deleted'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_team_id'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_member_id'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_scope'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_competition_id'), table_name='rankings')
    op.drop_table('rankings')
    # ### end Alembic commands ###
