"""add handicap history

Revision ID: f5a6b7c8d9e0
Revises: e4f5a6b7c8d9
Create Date: 2026-07-27 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a6b7c8d9e0'
down_revision: Union[str, None] = 'e4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handicap_history',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('old_handicap', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('new_handicap', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('source', sa.Enum('manual', 'competition', 'nz_golf_api', name='handicap_source', native_enum=False, length=16), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handicap_history_member_id'), 'handicap_history', ['member_id'], unique=False)
    op.create_index(op.f('ix_handicap_history_source'), 'handicap_history', ['source'], unique=False)
    op.create_index(op.f('ix_handicap_history_competition_id'), 'handicap_history', ['competition_id'], unique=False)
    op.create_index(op.f('ix_handicap_history_is_deleted'), 'handicap_history', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handicap_history_is_deleted'), table_name='handicap_history')
    op.drop_index(op.f('ix_handicap_history_competition_id'), table_name='handicap_history')
    op.drop_index(op.f('ix_handicap_history_source'), table_name='handicap_history')
    op.drop_index(op.f('ix_handicap_history_member_id'), table_name='handicap_history')
    op.drop_table('handicap_history')
    # ### end Alembic commands ###
